### ISSUE TITLE
SSH into MAINDB and collect data

### ISSUE THREAD

**Issue by mj-ctera** [ctera/ctools#16]
Add task to SSH into the Active DB and collect data.

**Comment by toddatctera** [comment]
Sean M wrote some code to create SSH keys and connect to a server. See [setup_auth](https://gitlab.com/sudo_dev_null/cterasdk-gui/-/blob/master/portal-upgrade-tool/portal_upgrade_tool.py#L178)

**Comment by toddatctera** [comment]
We may also be to use this program to make this easier:
https://github.com/amoffat/sh
